name: Eleventy Build TartanLlama

on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Build via TartanLlama
        uses: TartanLlama/actions-eleventy@master
        with:
          install_depencies: true
      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}