name: Eleventy Build TartanLlama

on:
  push:
    branches:
      - main

jobs:
  tartan_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build via 'TartanLlama/actions-eleventy'
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true

      - name: Deploy via 'actions-gh-pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}